---
swagger: "2.0"
info:
  description: >
    MyTravelBook is an application aim to provide a simple way to create a booktrip.
  title: MyTravelBook
  version: 1.0.0
x-tagGroups:
  - name: MyTravelBook management
    tags:
      - travel
consumes:
- application/json
produces:
- application/json
schemes:
- http
basePath: "/api/v1"
paths:
  /travel:
    $ref: ./travels.yaml
  /travel/{id}:
    $ref: ./travel.yaml


definitions:
  Travel:
    type: object
    required:
      - id
    properties:
      id:
        type: integer
        format: int64
        example: 10
      nameTravel:
        type: string
        description: Name of your trip
        example: 10 days in Poland 
      creationDate:
        type: string
        format: date-time
      country:
        type: string
        description: Country of the travel
        example: Lithuania 
      descriptionTravel:
        type: string
        description: Notes and resume of your trip !
        example: I visit Cracovie, Katowice and Warsaw, but to be honest my favorite city was Gdansk


