---
swagger: "2.0"
info:
  description: >
    "MyTravelBook is an application aim to provide a simple way to create and store your vacation stories." 
  title: "MyTravelBook"
  version: "1.0.0"
x-tagGroups:
  - name: "MyTravelBook management"
tags:
  - name: "travel"
    description: "Everything about travel"
  - name: "health"
    description: "Health status of MyTravelBook"
  - name: "login"
    description: "Login through oauth2 server"
  - name: "authentication"
    description: "Management access token"
consumes:
- "application/json"
produces:
- "application/json"
schemes:
- "http"
basePath: "/mytravelbook"

securityDefinitions:
  OauthSecurity:
    type: oauth2
    flow: accessCode
    authorizationUrl: 'https://accounts.google.com/o/oauth2/v2/auth'
    tokenUrl: 'https://www.googleapis.com/oauth2/v4/token'
    scopes:
      admin: Admin scope
      user: User scope

security:
  - OauthSecurity:
    - user

paths:
  /health:
    $ref: "./health.yaml"
  /travels:
    $ref: "./travels.yaml"
  /travel/{travelId}:
    $ref: "./travel.yaml"
  /login:
    $ref: "./login.yaml"
  /auth/callback:
    $ref: "./authentication.yaml"


definitions:

  # Default Error
  error:
    type: "object"
    required:
      - "message"
    properties:
      message:
        type: "string"
        minLength: 1
  
  # Health check
  health:
    type: "object"
    properties:
      status:
        type: "string" 

  # Travel
  travel:
    type: "object"
    required:
      - "name"
      - "country"
      - "description"
    properties:
      id:
        type: "integer"
        format: "int64"
        minimum: 1
      name:
        type: "string"
        description: "Name of your trip"
        minLength: 1
      country:
        type: "string"
        minLength: 1
      description:
        type: "string"
        minLength: 1
      creationDate:
        type: "string"
        format: "date-time"
      updatedAt:
        type: "string"
        format: "date-time"
  
  createTravelRequest:
    type: "object"
    required:
      - "name"
      - "country"
      - "description"
    properties:
      name:
        type: "string"
        minLength: 1
      country:
        type: "string"
        minLength: 1
      description:
        type: "string"
        minLength: 1

  updateTravelRequest:
    type: "object"
    required: 
      - "name"
      - "country"
      - "description"
    properties:
      name:
        type: "string"
        minLength: 1
      country:
        type: "string"
        minLength: 1
      description:
        type: "string"
        minLength: 1

  principal:
    type: string 

