---
swagger: "2.0"
info:
  description: >
    MyTravelNotebook is an application aim to provide a simple way to create a booktrip.
  title: MyTravelNotebook
  version: 1.0.0
x-tagGroups:
  - name: MyTravelNotebook management
    tags:
      - travel
consumes:
- application/json
produces:
- application/json
schemes:
- http
basePath: "/api/v1"
paths:
  /travels:
    $ref: ./travels.yaml
  /travel/{travel_id}:
    $ref: ./travel.yaml

definitions:

  # Travel
  travels:
    type: object
    required:
      - name
    properties:
      name:
        description: unique name of the travel
        type: string
        minLength: 1

  # Travel
  travel:
    type: object
    required:
      - name
    properties:
      travel_id:
        description: unique id of the travel
        type: string
        minLength: 1
      name:
        description: unique name of the travel
        type: string
        minLength: 1
      resume:
        description: short resume of the travel
        type: string
        minLength: 1
       
  # Default Error
  error:
    type: object
    required:
      - message
    properties:
      message:
        type: string
        minLength: 1

