// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"swagger_gen/swagger_gen/models"
)

// GetTravelOKCode is the HTTP code returned for type GetTravelOK
const GetTravelOKCode int = 200

/*GetTravelOK OK

swagger:response getTravelOK
*/
type GetTravelOK struct {

	/*
	  In: Body
	*/
	Payload *models.Travel `json:"body,omitempty"`
}

// NewGetTravelOK creates GetTravelOK with default headers values
func NewGetTravelOK() *GetTravelOK {

	return &GetTravelOK{}
}

// WithPayload adds the payload to the get travel o k response
func (o *GetTravelOK) WithPayload(payload *models.Travel) *GetTravelOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get travel o k response
func (o *GetTravelOK) SetPayload(payload *models.Travel) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetTravelOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
