// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetTravelHandlerFunc turns a function with the right signature into a get travel handler
type GetTravelHandlerFunc func(GetTravelParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetTravelHandlerFunc) Handle(params GetTravelParams) middleware.Responder {
	return fn(params)
}

// GetTravelHandler interface for that can handle valid get travel params
type GetTravelHandler interface {
	Handle(GetTravelParams) middleware.Responder
}

// NewGetTravel creates a new http.Handler for the get travel operation
func NewGetTravel(ctx *middleware.Context, handler GetTravelHandler) *GetTravel {
	return &GetTravel{Context: ctx, Handler: handler}
}

/* GetTravel swagger:route GET /travel getTravel

Returns a list of travels.

*/
type GetTravel struct {
	Context *middleware.Context
	Handler GetTravelHandler
}

func (o *GetTravel) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetTravelParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
