// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/loads"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/runtime/security"
	"github.com/go-openapi/spec"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/T-jegou/myTravelNotebook/swagger_gen/restapi/operations/authentication"
	"github.com/T-jegou/myTravelNotebook/swagger_gen/restapi/operations/health"
	"github.com/T-jegou/myTravelNotebook/swagger_gen/restapi/operations/login"
	"github.com/T-jegou/myTravelNotebook/swagger_gen/restapi/operations/travel"
)

// NewMyTravelBookAPI creates a new MyTravelBook instance
func NewMyTravelBookAPI(spec *loads.Document) *MyTravelBookAPI {
	return &MyTravelBookAPI{
		handlers:            make(map[string]map[string]http.Handler),
		formats:             strfmt.Default,
		defaultConsumes:     "application/json",
		defaultProduces:     "application/json",
		customConsumers:     make(map[string]runtime.Consumer),
		customProducers:     make(map[string]runtime.Producer),
		PreServerShutdown:   func() {},
		ServerShutdown:      func() {},
		spec:                spec,
		useSwaggerUI:        false,
		ServeError:          errors.ServeError,
		BasicAuthenticator:  security.BasicAuth,
		APIKeyAuthenticator: security.APIKeyAuth,
		BearerAuthenticator: security.BearerAuth,

		JSONConsumer: runtime.JSONConsumer(),

		JSONProducer: runtime.JSONProducer(),

		AuthenticationGetAuthCallbackHandler: authentication.GetAuthCallbackHandlerFunc(func(params authentication.GetAuthCallbackParams) middleware.Responder {
			return middleware.NotImplemented("operation authentication.GetAuthCallback has not yet been implemented")
		}),
		LoginGetLoginHandler: login.GetLoginHandlerFunc(func(params login.GetLoginParams) middleware.Responder {
			return middleware.NotImplemented("operation login.GetLogin has not yet been implemented")
		}),
		TravelAddTravelHandler: travel.AddTravelHandlerFunc(func(params travel.AddTravelParams) middleware.Responder {
			return middleware.NotImplemented("operation travel.AddTravel has not yet been implemented")
		}),
		TravelDeleteTravelByIDHandler: travel.DeleteTravelByIDHandlerFunc(func(params travel.DeleteTravelByIDParams) middleware.Responder {
			return middleware.NotImplemented("operation travel.DeleteTravelByID has not yet been implemented")
		}),
		HealthGetHealthHandler: health.GetHealthHandlerFunc(func(params health.GetHealthParams) middleware.Responder {
			return middleware.NotImplemented("operation health.GetHealth has not yet been implemented")
		}),
		TravelGetTravelByIDHandler: travel.GetTravelByIDHandlerFunc(func(params travel.GetTravelByIDParams) middleware.Responder {
			return middleware.NotImplemented("operation travel.GetTravelByID has not yet been implemented")
		}),
		TravelGetTravelsHandler: travel.GetTravelsHandlerFunc(func(params travel.GetTravelsParams) middleware.Responder {
			return middleware.NotImplemented("operation travel.GetTravels has not yet been implemented")
		}),
		TravelUpdateTravelByIDHandler: travel.UpdateTravelByIDHandlerFunc(func(params travel.UpdateTravelByIDParams) middleware.Responder {
			return middleware.NotImplemented("operation travel.UpdateTravelByID has not yet been implemented")
		}),
	}
}

/*MyTravelBookAPI "MyTravelBook is an application aim to provide a simple way to create and store your vacation stories."
 */
type MyTravelBookAPI struct {
	spec            *loads.Document
	context         *middleware.Context
	handlers        map[string]map[string]http.Handler
	formats         strfmt.Registry
	customConsumers map[string]runtime.Consumer
	customProducers map[string]runtime.Producer
	defaultConsumes string
	defaultProduces string
	Middleware      func(middleware.Builder) http.Handler
	useSwaggerUI    bool

	// BasicAuthenticator generates a runtime.Authenticator from the supplied basic auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	BasicAuthenticator func(security.UserPassAuthentication) runtime.Authenticator

	// APIKeyAuthenticator generates a runtime.Authenticator from the supplied token auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	APIKeyAuthenticator func(string, string, security.TokenAuthentication) runtime.Authenticator

	// BearerAuthenticator generates a runtime.Authenticator from the supplied bearer token auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	BearerAuthenticator func(string, security.ScopedTokenAuthentication) runtime.Authenticator

	// JSONConsumer registers a consumer for the following mime types:
	//   - application/json
	JSONConsumer runtime.Consumer

	// JSONProducer registers a producer for the following mime types:
	//   - application/json
	JSONProducer runtime.Producer

	// AuthenticationGetAuthCallbackHandler sets the operation handler for the get auth callback operation
	AuthenticationGetAuthCallbackHandler authentication.GetAuthCallbackHandler
	// LoginGetLoginHandler sets the operation handler for the get login operation
	LoginGetLoginHandler login.GetLoginHandler
	// TravelAddTravelHandler sets the operation handler for the add travel operation
	TravelAddTravelHandler travel.AddTravelHandler
	// TravelDeleteTravelByIDHandler sets the operation handler for the delete travel by Id operation
	TravelDeleteTravelByIDHandler travel.DeleteTravelByIDHandler
	// HealthGetHealthHandler sets the operation handler for the get health operation
	HealthGetHealthHandler health.GetHealthHandler
	// TravelGetTravelByIDHandler sets the operation handler for the get travel by Id operation
	TravelGetTravelByIDHandler travel.GetTravelByIDHandler
	// TravelGetTravelsHandler sets the operation handler for the get travels operation
	TravelGetTravelsHandler travel.GetTravelsHandler
	// TravelUpdateTravelByIDHandler sets the operation handler for the update travel by Id operation
	TravelUpdateTravelByIDHandler travel.UpdateTravelByIDHandler

	// ServeError is called when an error is received, there is a default handler
	// but you can set your own with this
	ServeError func(http.ResponseWriter, *http.Request, error)

	// PreServerShutdown is called before the HTTP(S) server is shutdown
	// This allows for custom functions to get executed before the HTTP(S) server stops accepting traffic
	PreServerShutdown func()

	// ServerShutdown is called when the HTTP(S) server is shut down and done
	// handling all active connections and does not accept connections any more
	ServerShutdown func()

	// Custom command line argument groups with their descriptions
	CommandLineOptionsGroups []swag.CommandLineOptionsGroup

	// User defined logger function.
	Logger func(string, ...interface{})
}

// UseRedoc for documentation at /docs
func (o *MyTravelBookAPI) UseRedoc() {
	o.useSwaggerUI = false
}

// UseSwaggerUI for documentation at /docs
func (o *MyTravelBookAPI) UseSwaggerUI() {
	o.useSwaggerUI = true
}

// SetDefaultProduces sets the default produces media type
func (o *MyTravelBookAPI) SetDefaultProduces(mediaType string) {
	o.defaultProduces = mediaType
}

// SetDefaultConsumes returns the default consumes media type
func (o *MyTravelBookAPI) SetDefaultConsumes(mediaType string) {
	o.defaultConsumes = mediaType
}

// SetSpec sets a spec that will be served for the clients.
func (o *MyTravelBookAPI) SetSpec(spec *loads.Document) {
	o.spec = spec
}

// DefaultProduces returns the default produces media type
func (o *MyTravelBookAPI) DefaultProduces() string {
	return o.defaultProduces
}

// DefaultConsumes returns the default consumes media type
func (o *MyTravelBookAPI) DefaultConsumes() string {
	return o.defaultConsumes
}

// Formats returns the registered string formats
func (o *MyTravelBookAPI) Formats() strfmt.Registry {
	return o.formats
}

// RegisterFormat registers a custom format validator
func (o *MyTravelBookAPI) RegisterFormat(name string, format strfmt.Format, validator strfmt.Validator) {
	o.formats.Add(name, format, validator)
}

// Validate validates the registrations in the MyTravelBookAPI
func (o *MyTravelBookAPI) Validate() error {
	var unregistered []string

	if o.JSONConsumer == nil {
		unregistered = append(unregistered, "JSONConsumer")
	}

	if o.JSONProducer == nil {
		unregistered = append(unregistered, "JSONProducer")
	}

	if o.AuthenticationGetAuthCallbackHandler == nil {
		unregistered = append(unregistered, "authentication.GetAuthCallbackHandler")
	}
	if o.LoginGetLoginHandler == nil {
		unregistered = append(unregistered, "login.GetLoginHandler")
	}
	if o.TravelAddTravelHandler == nil {
		unregistered = append(unregistered, "travel.AddTravelHandler")
	}
	if o.TravelDeleteTravelByIDHandler == nil {
		unregistered = append(unregistered, "travel.DeleteTravelByIDHandler")
	}
	if o.HealthGetHealthHandler == nil {
		unregistered = append(unregistered, "health.GetHealthHandler")
	}
	if o.TravelGetTravelByIDHandler == nil {
		unregistered = append(unregistered, "travel.GetTravelByIDHandler")
	}
	if o.TravelGetTravelsHandler == nil {
		unregistered = append(unregistered, "travel.GetTravelsHandler")
	}
	if o.TravelUpdateTravelByIDHandler == nil {
		unregistered = append(unregistered, "travel.UpdateTravelByIDHandler")
	}

	if len(unregistered) > 0 {
		return fmt.Errorf("missing registration: %s", strings.Join(unregistered, ", "))
	}

	return nil
}

// ServeErrorFor gets a error handler for a given operation id
func (o *MyTravelBookAPI) ServeErrorFor(operationID string) func(http.ResponseWriter, *http.Request, error) {
	return o.ServeError
}

// AuthenticatorsFor gets the authenticators for the specified security schemes
func (o *MyTravelBookAPI) AuthenticatorsFor(schemes map[string]spec.SecurityScheme) map[string]runtime.Authenticator {
	return nil
}

// Authorizer returns the registered authorizer
func (o *MyTravelBookAPI) Authorizer() runtime.Authorizer {
	return nil
}

// ConsumersFor gets the consumers for the specified media types.
// MIME type parameters are ignored here.
func (o *MyTravelBookAPI) ConsumersFor(mediaTypes []string) map[string]runtime.Consumer {
	result := make(map[string]runtime.Consumer, len(mediaTypes))
	for _, mt := range mediaTypes {
		switch mt {
		case "application/json":
			result["application/json"] = o.JSONConsumer
		}

		if c, ok := o.customConsumers[mt]; ok {
			result[mt] = c
		}
	}
	return result
}

// ProducersFor gets the producers for the specified media types.
// MIME type parameters are ignored here.
func (o *MyTravelBookAPI) ProducersFor(mediaTypes []string) map[string]runtime.Producer {
	result := make(map[string]runtime.Producer, len(mediaTypes))
	for _, mt := range mediaTypes {
		switch mt {
		case "application/json":
			result["application/json"] = o.JSONProducer
		}

		if p, ok := o.customProducers[mt]; ok {
			result[mt] = p
		}
	}
	return result
}

// HandlerFor gets a http.Handler for the provided operation method and path
func (o *MyTravelBookAPI) HandlerFor(method, path string) (http.Handler, bool) {
	if o.handlers == nil {
		return nil, false
	}
	um := strings.ToUpper(method)
	if _, ok := o.handlers[um]; !ok {
		return nil, false
	}
	if path == "/" {
		path = ""
	}
	h, ok := o.handlers[um][path]
	return h, ok
}

// Context returns the middleware context for the my travel book API
func (o *MyTravelBookAPI) Context() *middleware.Context {
	if o.context == nil {
		o.context = middleware.NewRoutableContext(o.spec, o, nil)
	}

	return o.context
}

func (o *MyTravelBookAPI) initHandlerCache() {
	o.Context() // don't care about the result, just that the initialization happened
	if o.handlers == nil {
		o.handlers = make(map[string]map[string]http.Handler)
	}

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/auth/callback"] = authentication.NewGetAuthCallback(o.context, o.AuthenticationGetAuthCallbackHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/login"] = login.NewGetLogin(o.context, o.LoginGetLoginHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/travels"] = travel.NewAddTravel(o.context, o.TravelAddTravelHandler)
	if o.handlers["DELETE"] == nil {
		o.handlers["DELETE"] = make(map[string]http.Handler)
	}
	o.handlers["DELETE"]["/travel/{travelId}"] = travel.NewDeleteTravelByID(o.context, o.TravelDeleteTravelByIDHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/health"] = health.NewGetHealth(o.context, o.HealthGetHealthHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/travel/{travelId}"] = travel.NewGetTravelByID(o.context, o.TravelGetTravelByIDHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/travels"] = travel.NewGetTravels(o.context, o.TravelGetTravelsHandler)
	if o.handlers["PUT"] == nil {
		o.handlers["PUT"] = make(map[string]http.Handler)
	}
	o.handlers["PUT"]["/travel/{travelId}"] = travel.NewUpdateTravelByID(o.context, o.TravelUpdateTravelByIDHandler)
}

// Serve creates a http handler to serve the API over HTTP
// can be used directly in http.ListenAndServe(":8000", api.Serve(nil))
func (o *MyTravelBookAPI) Serve(builder middleware.Builder) http.Handler {
	o.Init()

	if o.Middleware != nil {
		return o.Middleware(builder)
	}
	if o.useSwaggerUI {
		return o.context.APIHandlerSwaggerUI(builder)
	}
	return o.context.APIHandler(builder)
}

// Init allows you to just initialize the handler cache, you can then recompose the middleware as you see fit
func (o *MyTravelBookAPI) Init() {
	if len(o.handlers) == 0 {
		o.initHandlerCache()
	}
}

// RegisterConsumer allows you to add (or override) a consumer for a media type.
func (o *MyTravelBookAPI) RegisterConsumer(mediaType string, consumer runtime.Consumer) {
	o.customConsumers[mediaType] = consumer
}

// RegisterProducer allows you to add (or override) a producer for a media type.
func (o *MyTravelBookAPI) RegisterProducer(mediaType string, producer runtime.Producer) {
	o.customProducers[mediaType] = producer
}

// AddMiddlewareFor adds a http middleware to existing handler
func (o *MyTravelBookAPI) AddMiddlewareFor(method, path string, builder middleware.Builder) {
	um := strings.ToUpper(method)
	if path == "/" {
		path = ""
	}
	o.Init()
	if h, ok := o.handlers[um][path]; ok {
		o.handlers[method][path] = builder(h)
	}
}
