// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Travel travel
//
// swagger:model travel
type Travel struct {

	// unique name of the travel
	// Required: true
	// Min Length: 1
	Name *string `json:"name"`

	// short resume of the travel
	// Min Length: 1
	Resume string `json:"resume,omitempty"`

	// unique id of the travel
	// Min Length: 1
	TravelID string `json:"travel_id,omitempty"`
}

// Validate validates this travel
func (m *Travel) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateResume(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTravelID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Travel) validateName(formats strfmt.Registry) error {

	if err := validate.Required("name", "body", m.Name); err != nil {
		return err
	}

	if err := validate.MinLength("name", "body", *m.Name, 1); err != nil {
		return err
	}

	return nil
}

func (m *Travel) validateResume(formats strfmt.Registry) error {
	if swag.IsZero(m.Resume) { // not required
		return nil
	}

	if err := validate.MinLength("resume", "body", m.Resume, 1); err != nil {
		return err
	}

	return nil
}

func (m *Travel) validateTravelID(formats strfmt.Registry) error {
	if swag.IsZero(m.TravelID) { // not required
		return nil
	}

	if err := validate.MinLength("travel_id", "body", m.TravelID, 1); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this travel based on context it is used
func (m *Travel) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Travel) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Travel) UnmarshalBinary(b []byte) error {
	var res Travel
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
