swagger: '2.0'
info:
  description: >
    "MyTravelBook is an application aim to provide a simple way to create and
    store your vacation stories." 
  title: MyTravelBook
  version: 1.0.0
x-tagGroups:
  - name: MyTravelBook management
tags:
  - name: travel
    description: Everything about travel
  - name: health
    description: Health status of MyTravelBook
  - name: login
    description: Login through oauth2 server
  - name: authentication
    description: Management access token
consumes:
  - application/json
produces:
  - application/json
schemes:
  - http
basePath: /mytravelbook
securityDefinitions:
  OauthSecurity:
    type: oauth2
    flow: accessCode
    authorizationUrl: https://accounts.google.com/o/oauth2/v2/auth
    tokenUrl: https://www.googleapis.com/oauth2/v4/token
    scopes:
      admin: Admin scope
      user: User scope
paths:
  /health:
    get:
      tags:
        - health
      operationId: getHealth
      description: Check if MyTravelBook is healthy
      responses:
        '200':
          description: status of health check
          schema:
            $ref: '#/definitions/health'
        default:
          description: generic error response
          schema:
            $ref: '#/definitions/error'
  /travels:
    get:
      tags:
        - travel
      summary: Returns an array of travels object.
      operationId: getTravels
      produces:
        - application/json
      responses:
        '200':
          description: list all the travels
          schema:
            type: array
            items:
              $ref: '#/definitions/travel'
        default:
          description: generic error response
          schema:
            $ref: '#/definitions/error'
    post:
      tags:
        - travel
      summary: Add a new travel to the shelf
      operationId: addTravel
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: Create a travel object
          required: true
          schema:
            $ref: '#/definitions/createTravelRequest'
      responses:
        '200':
          description: returns the created travel
          schema:
            $ref: '#/definitions/travel'
        default:
          description: generic error response
          schema:
            $ref: '#/definitions/error'
  /travel/{travelId}:
    get:
      tags:
        - travel
      summary: Find travel by ID
      operationId: getTravelById
      produces:
        - application/json
      parameters:
        - in: path
          name: travelId
          description: id travel to be retrieve
          required: true
          type: integer
          format: int64
          minimum: 1
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/travel'
        default:
          description: generic error response
          schema:
            $ref: '#/definitions/error'
    put:
      tags:
        - travel
      summary: Update an existing travel by ID
      operationId: updateTravelById
      parameters:
        - in: path
          name: travelId
          description: id's travel that need to be updated
          required: true
          type: integer
          format: int64
        - in: body
          name: body
          description: Updated user object
          required: true
          schema:
            $ref: '#/definitions/updateTravelRequest'
      responses:
        '200':
          description: return the updateted travel
          schema:
            $ref: '#/definitions/travel'
        default:
          description: generic error response
          schema:
            $ref: '#/definitions/error'
    delete:
      tags:
        - travel
      summary: Delete an existing travel using his Id
      operationId: deleteTravelById
      parameters:
        - in: path
          name: travelId
          description: numeric ID of the flag
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: Travel successfuly deleted
        default:
          description: generic error response
          schema:
            $ref: '#/definitions/error'
  /login:
    get:
      tags:
        - login
      summary: login through oauth2 server
      security: []
      responses:
        '200':
          description: login
          schema:
            properties:
              access_token:
                type: string
                format: string
        default:
          description: error
          schema:
            $ref: '#/definitions/error'
  /auth/callback:
    get:
      tags:
        - authentication
      summary: return access_token
      security: []
      responses:
        '200':
          description: login
          schema:
            properties:
              access_token:
                type: string
                format: string
        default:
          description: error
          schema:
            $ref: '#/definitions/error'
definitions:
  error:
    type: object
    required:
      - message
    properties:
      message:
        type: string
        minLength: 1
  health:
    type: object
    properties:
      status:
        type: string
  travel:
    type: object
    required:
      - name
      - country
      - description
    properties:
      id:
        type: integer
        format: int64
        minimum: 1
      name:
        type: string
        description: Name of your trip
        minLength: 1
      country:
        type: string
        minLength: 1
      description:
        type: string
        minLength: 1
      creationDate:
        type: string
        format: date-time
      updatedAt:
        type: string
        format: date-time
  createTravelRequest:
    type: object
    required:
      - name
      - country
      - description
    properties:
      name:
        type: string
        minLength: 1
      country:
        type: string
        minLength: 1
      description:
        type: string
        minLength: 1
  updateTravelRequest:
    type: object
    required:
      - name
      - country
      - description
    properties:
      name:
        type: string
        minLength: 1
      country:
        type: string
        minLength: 1
      description:
        type: string
        minLength: 1
  principal:
    type: string
