swagger: '2.0'
info:
  description: >
    MyTravelBook is an application aim to provide a simple way to create a
    booktrip.
  title: MyTravelBook
  version: 1.0.0
x-tagGroups:
  - name: MyTravelBook management
    tags:
      - travel
consumes:
  - application/json
produces:
  - application/json
schemes:
  - http
basePath: /api/v1
paths:
  /travel:
    get:
      tags:
        - travel
      summary: Returns a list of travels.
      description: ''
      operationId: getTravels
      produces:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Travel'
    post:
      tags:
        - travel
      summary: Add a new travel to the shelf
      description: ''
      operationId: addTravel
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: nameTravel
          description: Travel object that need to be added to the shelf
          required: true
          schema:
            $ref: '#/definitions/Travel'
      responses:
        '200':
          description: Succesful operation
        '405':
          description: Invalid input
  /travel/{id}:
    get:
      tags:
        - travel
      summary: Find travel by ID
      description: Returns a single travel
      operationId: getTravelById
      produces:
        - application/json
      parameters:
        - name: id
          in: path
          description: id's travel to be retrieve
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/Travel'
        '400':
          description: Invalid ID supplied
        '404':
          description: Travel not found
    put:
      tags:
        - travel
      summary: Update an existing travel by ID
      description: ''
      operationId: updateTravelById
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: id
          in: path
          description: id's travel that need to be updated
          required: true
          type: integer
        - in: body
          name: body
          description: Updated user object
          required: true
          schema:
            $ref: '#/definitions/Travel'
      responses:
        '200':
          description: Travel succesfully updated
        '400':
          description: Invalid Travel supplied
        '404':
          description: User not found
    delete:
      tags:
        - travel
      summary: Delete an existing travel using his Id
      description: ''
      operationId: deleteTravelById
      produces:
        - application/json
      parameters:
        - name: id
          in: path
          description: id's travel to delete
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: Travel successfuly deleted
        '400':
          description: Invalid ID supplied
        '404':
          description: Travel not found
definitions:
  Travel:
    type: object
    required:
      - id
    properties:
      id:
        type: integer
        format: int64
        example: 10
      nameTravel:
        type: string
        description: Name of your trip
        example: 10 days in Poland
      creationDate:
        type: string
        format: date-time
      country:
        type: string
        description: Country of the travel
        example: Lithuania
      descriptionTravel:
        type: string
        description: Notes and resume of your trip !
        example: >-
          I visit Cracovie, Katowice and Warsaw, but to be honest my favorite
          city was Gdansk
