swagger: '2.0'
info:
  description: >
    MyTravelNotebook is an application aim to provide a simple way to create a
    booktrip.
  title: MyTravelNotebook
  version: 1.0.0
x-tagGroups:
  - name: MyTravelNotebook management
    tags:
      - travel
consumes:
  - application/json
produces:
  - application/json
schemes:
  - http
basePath: /api/v1
paths:
  /travel:
    get:
      tags:
        - travel
      operationId: getTravels
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/definitions/Travel'
    post:
      tags:
        - travel
      summary: Create new travel
      description: Create a new travel using form
      operationId: createTravel
      requestBody:
        description: Created travel object
        content:
          application/json:
            schema:
              $ref: '#/definitions/Travel'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/definitions/Travel'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/definitions/Travel'
  /travel/{id}:
    get:
      tags:
        - travel
      summary: Find travel by ID
      description: Returns a single travel
      operationId: getTravelById
      parameters:
        - name: id
          in: path
          description: ID of travel to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: returns the travel information
          schema:
            type: array
            items:
              $ref: '#/definitions/Travel'
        '404':
          description: Travel not found
    delete:
      tags:
        - travel
      summary: Delete a travel
      description: delete a travel by using his unique ID
      operationId: deleteTravelById
      parameters:
        - name: id
          in: path
          description: travel id to delete
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: The resource was deleted successfully.
        '400':
          description: Invalid travel value, bad request
        '404':
          description: Travel not found
    put:
      tags:
        - travel
      summary: Update an exisiting travel
      description: Update a travel by using his unique ID
      operationId: updateTravelById
      parameters:
        - name: id
          in: path
          description: travel id to delete
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        description: Created travel object
        content:
          application/json:
            schema:
              $ref: '#/definitions/Travel'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/definitions/Travel'
      responses:
        '204':
          description: The resource was updtated successfully.
          content:
            application/json:
              schema:
                $ref: '#/definitions/Travel'
        '400':
          description: Invalid travel value, bad request
        '404':
          description: Travel not found
definitions:
  Travel:
    type: object
    properties:
      id:
        type: integer
        format: int64
        example: 10
      tripName:
        type: string
        description: Name of your trip
        example: 10 days in Poland
      creationDate:
        type: string
        format: date-time
      country:
        type: string
        description: Country of the travel
        example: Lithuania
      descriptionTravel:
        type: string
        description: Notes and resume of your trip !
        example: >-
          I visit Cracovie, Katowice and Warsaw, but to be honest my favorite
          city was Gdansk
