// Code generated by go-swagger; DO NOT EDIT.

package travel

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// AddTravelHandlerFunc turns a function with the right signature into a add travel handler
type AddTravelHandlerFunc func(AddTravelParams) middleware.Responder

// Handle executing the request and returning a response
func (fn AddTravelHandlerFunc) Handle(params AddTravelParams) middleware.Responder {
	return fn(params)
}

// AddTravelHandler interface for that can handle valid add travel params
type AddTravelHandler interface {
	Handle(AddTravelParams) middleware.Responder
}

// NewAddTravel creates a new http.Handler for the add travel operation
func NewAddTravel(ctx *middleware.Context, handler AddTravelHandler) *AddTravel {
	return &AddTravel{Context: ctx, Handler: handler}
}

/* AddTravel swagger:route POST /travel travel addTravel

Add a new travel to the shelf

*/
type AddTravel struct {
	Context *middleware.Context
	Handler AddTravelHandler
}

func (o *AddTravel) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewAddTravelParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
