// Code generated by go-swagger; DO NOT EDIT.

package travel

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/T-jegou/myTravelNotebook/swagger_gen/models"
)

// DeleteTravelByIDOKCode is the HTTP code returned for type DeleteTravelByIDOK
const DeleteTravelByIDOKCode int = 200

/*DeleteTravelByIDOK Travel successfuly deleted

swagger:response deleteTravelByIdOK
*/
type DeleteTravelByIDOK struct {
}

// NewDeleteTravelByIDOK creates DeleteTravelByIDOK with default headers values
func NewDeleteTravelByIDOK() *DeleteTravelByIDOK {

	return &DeleteTravelByIDOK{}
}

// WriteResponse to the client
func (o *DeleteTravelByIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

/*DeleteTravelByIDDefault generic error response

swagger:response deleteTravelByIdDefault
*/
type DeleteTravelByIDDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteTravelByIDDefault creates DeleteTravelByIDDefault with default headers values
func NewDeleteTravelByIDDefault(code int) *DeleteTravelByIDDefault {
	if code <= 0 {
		code = 500
	}

	return &DeleteTravelByIDDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the delete travel by Id default response
func (o *DeleteTravelByIDDefault) WithStatusCode(code int) *DeleteTravelByIDDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the delete travel by Id default response
func (o *DeleteTravelByIDDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the delete travel by Id default response
func (o *DeleteTravelByIDDefault) WithPayload(payload *models.Error) *DeleteTravelByIDDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete travel by Id default response
func (o *DeleteTravelByIDDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteTravelByIDDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
