// Code generated by go-swagger; DO NOT EDIT.

package travel

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DeleteTravelByIDOKCode is the HTTP code returned for type DeleteTravelByIDOK
const DeleteTravelByIDOKCode int = 200

/*DeleteTravelByIDOK Travel successfuly deleted

swagger:response deleteTravelByIdOK
*/
type DeleteTravelByIDOK struct {
}

// NewDeleteTravelByIDOK creates DeleteTravelByIDOK with default headers values
func NewDeleteTravelByIDOK() *DeleteTravelByIDOK {

	return &DeleteTravelByIDOK{}
}

// WriteResponse to the client
func (o *DeleteTravelByIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// DeleteTravelByIDBadRequestCode is the HTTP code returned for type DeleteTravelByIDBadRequest
const DeleteTravelByIDBadRequestCode int = 400

/*DeleteTravelByIDBadRequest Invalid ID supplied

swagger:response deleteTravelByIdBadRequest
*/
type DeleteTravelByIDBadRequest struct {
}

// NewDeleteTravelByIDBadRequest creates DeleteTravelByIDBadRequest with default headers values
func NewDeleteTravelByIDBadRequest() *DeleteTravelByIDBadRequest {

	return &DeleteTravelByIDBadRequest{}
}

// WriteResponse to the client
func (o *DeleteTravelByIDBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// DeleteTravelByIDNotFoundCode is the HTTP code returned for type DeleteTravelByIDNotFound
const DeleteTravelByIDNotFoundCode int = 404

/*DeleteTravelByIDNotFound Travel not found

swagger:response deleteTravelByIdNotFound
*/
type DeleteTravelByIDNotFound struct {
}

// NewDeleteTravelByIDNotFound creates DeleteTravelByIDNotFound with default headers values
func NewDeleteTravelByIDNotFound() *DeleteTravelByIDNotFound {

	return &DeleteTravelByIDNotFound{}
}

// WriteResponse to the client
func (o *DeleteTravelByIDNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
