// Code generated by go-swagger; DO NOT EDIT.

package travel

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// NewGetTravelByIDParams creates a new GetTravelByIDParams object
//
// There are no default values defined in the spec.
func NewGetTravelByIDParams() GetTravelByIDParams {

	return GetTravelByIDParams{}
}

// GetTravelByIDParams contains all the bound params for the get travel by Id operation
// typically these are obtained from a http.Request
//
// swagger:parameters getTravelById
type GetTravelByIDParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*id travel to be retrieve
	  Required: true
	  Minimum: 1
	  In: path
	*/
	TravelID int64
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetTravelByIDParams() beforehand.
func (o *GetTravelByIDParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rTravelID, rhkTravelID, _ := route.Params.GetOK("travelId")
	if err := o.bindTravelID(rTravelID, rhkTravelID, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindTravelID binds and validates parameter TravelID from path.
func (o *GetTravelByIDParams) bindTravelID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	value, err := swag.ConvertInt64(raw)
	if err != nil {
		return errors.InvalidType("travelId", "path", "int64", raw)
	}
	o.TravelID = value

	if err := o.validateTravelID(formats); err != nil {
		return err
	}

	return nil
}

// validateTravelID carries on validations for parameter TravelID
func (o *GetTravelByIDParams) validateTravelID(formats strfmt.Registry) error {

	if err := validate.MinimumInt("travelId", "path", o.TravelID, 1, false); err != nil {
		return err
	}

	return nil
}
