// Code generated by go-swagger; DO NOT EDIT.

package travel

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/T-jegou/myTravelNotebook/swagger_gen/models"
)

// GetTravelByIDHandlerFunc turns a function with the right signature into a get travel by Id handler
type GetTravelByIDHandlerFunc func(GetTravelByIDParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn GetTravelByIDHandlerFunc) Handle(params GetTravelByIDParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// GetTravelByIDHandler interface for that can handle valid get travel by Id params
type GetTravelByIDHandler interface {
	Handle(GetTravelByIDParams, *models.Principal) middleware.Responder
}

// NewGetTravelByID creates a new http.Handler for the get travel by Id operation
func NewGetTravelByID(ctx *middleware.Context, handler GetTravelByIDHandler) *GetTravelByID {
	return &GetTravelByID{Context: ctx, Handler: handler}
}

/* GetTravelByID swagger:route GET /travel/{travelId} travel getTravelById

Find travel by ID

*/
type GetTravelByID struct {
	Context *middleware.Context
	Handler GetTravelByIDHandler
}

func (o *GetTravelByID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetTravelByIDParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
