// Code generated by go-swagger; DO NOT EDIT.

package travel

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"swagger_gen/swagger_gen/models"
)

// ListTravelsOKCode is the HTTP code returned for type ListTravelsOK
const ListTravelsOKCode int = 200

/*ListTravelsOK list all the travels

swagger:response listTravelsOK
*/
type ListTravelsOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Travels `json:"body,omitempty"`
}

// NewListTravelsOK creates ListTravelsOK with default headers values
func NewListTravelsOK() *ListTravelsOK {

	return &ListTravelsOK{}
}

// WithPayload adds the payload to the list travels o k response
func (o *ListTravelsOK) WithPayload(payload []*models.Travels) *ListTravelsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list travels o k response
func (o *ListTravelsOK) SetPayload(payload []*models.Travels) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListTravelsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.Travels, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

/*ListTravelsDefault generic error response

swagger:response listTravelsDefault
*/
type ListTravelsDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewListTravelsDefault creates ListTravelsDefault with default headers values
func NewListTravelsDefault(code int) *ListTravelsDefault {
	if code <= 0 {
		code = 500
	}

	return &ListTravelsDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the list travels default response
func (o *ListTravelsDefault) WithStatusCode(code int) *ListTravelsDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the list travels default response
func (o *ListTravelsDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the list travels default response
func (o *ListTravelsDefault) WithPayload(payload *models.Error) *ListTravelsDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list travels default response
func (o *ListTravelsDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListTravelsDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
