// Code generated by go-swagger; DO NOT EDIT.

package travel

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// UpdateTravelOKCode is the HTTP code returned for type UpdateTravelOK
const UpdateTravelOKCode int = 200

/*UpdateTravelOK Travel succesfully updated

swagger:response updateTravelOK
*/
type UpdateTravelOK struct {
}

// NewUpdateTravelOK creates UpdateTravelOK with default headers values
func NewUpdateTravelOK() *UpdateTravelOK {

	return &UpdateTravelOK{}
}

// WriteResponse to the client
func (o *UpdateTravelOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// UpdateTravelBadRequestCode is the HTTP code returned for type UpdateTravelBadRequest
const UpdateTravelBadRequestCode int = 400

/*UpdateTravelBadRequest Invalid Travel supplied

swagger:response updateTravelBadRequest
*/
type UpdateTravelBadRequest struct {
}

// NewUpdateTravelBadRequest creates UpdateTravelBadRequest with default headers values
func NewUpdateTravelBadRequest() *UpdateTravelBadRequest {

	return &UpdateTravelBadRequest{}
}

// WriteResponse to the client
func (o *UpdateTravelBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// UpdateTravelNotFoundCode is the HTTP code returned for type UpdateTravelNotFound
const UpdateTravelNotFoundCode int = 404

/*UpdateTravelNotFound User not found

swagger:response updateTravelNotFound
*/
type UpdateTravelNotFound struct {
}

// NewUpdateTravelNotFound creates UpdateTravelNotFound with default headers values
func NewUpdateTravelNotFound() *UpdateTravelNotFound {

	return &UpdateTravelNotFound{}
}

// WriteResponse to the client
func (o *UpdateTravelNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
