// Code generated by go-swagger; DO NOT EDIT.

package travel

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// UpdateTravelByIDOKCode is the HTTP code returned for type UpdateTravelByIDOK
const UpdateTravelByIDOKCode int = 200

/*UpdateTravelByIDOK Travel succesfully updated

swagger:response updateTravelByIdOK
*/
type UpdateTravelByIDOK struct {
}

// NewUpdateTravelByIDOK creates UpdateTravelByIDOK with default headers values
func NewUpdateTravelByIDOK() *UpdateTravelByIDOK {

	return &UpdateTravelByIDOK{}
}

// WriteResponse to the client
func (o *UpdateTravelByIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// UpdateTravelByIDBadRequestCode is the HTTP code returned for type UpdateTravelByIDBadRequest
const UpdateTravelByIDBadRequestCode int = 400

/*UpdateTravelByIDBadRequest Invalid Travel supplied

swagger:response updateTravelByIdBadRequest
*/
type UpdateTravelByIDBadRequest struct {
}

// NewUpdateTravelByIDBadRequest creates UpdateTravelByIDBadRequest with default headers values
func NewUpdateTravelByIDBadRequest() *UpdateTravelByIDBadRequest {

	return &UpdateTravelByIDBadRequest{}
}

// WriteResponse to the client
func (o *UpdateTravelByIDBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// UpdateTravelByIDNotFoundCode is the HTTP code returned for type UpdateTravelByIDNotFound
const UpdateTravelByIDNotFoundCode int = 404

/*UpdateTravelByIDNotFound User not found

swagger:response updateTravelByIdNotFound
*/
type UpdateTravelByIDNotFound struct {
}

// NewUpdateTravelByIDNotFound creates UpdateTravelByIDNotFound with default headers values
func NewUpdateTravelByIDNotFound() *UpdateTravelByIDNotFound {

	return &UpdateTravelByIDNotFound{}
}

// WriteResponse to the client
func (o *UpdateTravelByIDNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
