// Code generated by go-swagger; DO NOT EDIT.

package travel

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// UpdateTravelHandlerFunc turns a function with the right signature into a update travel handler
type UpdateTravelHandlerFunc func(UpdateTravelParams) middleware.Responder

// Handle executing the request and returning a response
func (fn UpdateTravelHandlerFunc) Handle(params UpdateTravelParams) middleware.Responder {
	return fn(params)
}

// UpdateTravelHandler interface for that can handle valid update travel params
type UpdateTravelHandler interface {
	Handle(UpdateTravelParams) middleware.Responder
}

// NewUpdateTravel creates a new http.Handler for the update travel operation
func NewUpdateTravel(ctx *middleware.Context, handler UpdateTravelHandler) *UpdateTravel {
	return &UpdateTravel{Context: ctx, Handler: handler}
}

/* UpdateTravel swagger:route PUT /travel/{id} travel updateTravel

Updated travel

*/
type UpdateTravel struct {
	Context *middleware.Context
	Handler UpdateTravelHandler
}

func (o *UpdateTravel) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewUpdateTravelParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
