// Code generated by go-swagger; DO NOT EDIT.

package travel

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// UpdateTravelByIDHandlerFunc turns a function with the right signature into a update travel by Id handler
type UpdateTravelByIDHandlerFunc func(UpdateTravelByIDParams) middleware.Responder

// Handle executing the request and returning a response
func (fn UpdateTravelByIDHandlerFunc) Handle(params UpdateTravelByIDParams) middleware.Responder {
	return fn(params)
}

// UpdateTravelByIDHandler interface for that can handle valid update travel by Id params
type UpdateTravelByIDHandler interface {
	Handle(UpdateTravelByIDParams) middleware.Responder
}

// NewUpdateTravelByID creates a new http.Handler for the update travel by Id operation
func NewUpdateTravelByID(ctx *middleware.Context, handler UpdateTravelByIDHandler) *UpdateTravelByID {
	return &UpdateTravelByID{Context: ctx, Handler: handler}
}

/* UpdateTravelByID swagger:route PUT /travel/{travelId} travel updateTravelById

Update an existing travel by ID

*/
type UpdateTravelByID struct {
	Context *middleware.Context
	Handler UpdateTravelByIDHandler
}

func (o *UpdateTravelByID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewUpdateTravelByIDParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
