// Code generated by go-swagger; DO NOT EDIT.

// Package restapi MyTravelBook
//
//  MyTravelBook is an application aim to provide a simple way to create a booktrip.
//
//  Schemes:
//    http
//  Host: localhost
//  BasePath: /api/v1
//  Version: 1.0.0
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//
// swagger:meta
package restapi
